# Generated by Django 4.0.4 on 2022-05-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_usermodel_prof_image_usermodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_searched',
            field=models.TextField(blank=True),
        ),
    ]
