# Generated by Django 4.0.4 on 2022-05-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_usermodel_last_searched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_searched',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
