# Generated by Django 4.0.4 on 2022-05-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('property_radious', models.FloatField(blank=True, default=0.0)),
                ('property_price', models.FloatField(blank=True, default=0.0)),
                ('property_purpose', models.CharField(max_length=10)),
                ('property_city', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyapp.propertytypesmodel')),
            ],
        ),
    ]
