# Generated by Django 4.0.4 on 2022-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
