# Generated by Django 4.0.4 on 2022-05-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0002_remove_propertymodel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='property_type',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='PropertyTypesModel',
        ),
    ]
