# Generated by Django 4.0.4 on 2022-05-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0003_alter_propertymodel_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='property_bath',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='property_bed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='property_room',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='residential_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
