# Generated by Django 4.0.4 on 2022-05-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0004_propertymodel_property_bath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedpropertymodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='likedpropertymodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='broucher',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='Image')),
                ('image_purpose', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyapp.propertymodel')),
            ],
        ),
    ]
