# Generated by Django 4.0.4 on 2022-05-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0005_alter_propertymodel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
