# Generated by Django 4.0.4 on 2022-05-31 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0006_alter_imagesmodel_image_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(max_length=100)),
                ('far', models.FloatField(default=0.0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyapp.propertymodel')),
            ],
        ),
    ]
