# Generated by Django 4.0.4 on 2022-05-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0006_alter_propertymodel_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymodel',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
